version = 1

[global]
dll = "/home/luke/.local/share/Steam/steamapps/common/Lossless Scaling/Lossless.dll"

[[game]]
exe = "NeedForSpeedHeat"
multiplier = 2
flow_scale = 0.7
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"
