# Font
font_family DMMonoNerdFont
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0

# Cursor
cursor #eeeef5
cursor_shape beam
cursor_shape_unfocused unchanged

# Scrollback
scrollbar scrolled-and-hovered
scrollbar_width 0.3
scrollbar_hover_width 0.65
scrollbar_radius 0.3
scrollbar_hitbox_expansion 6
scrollbar_handle_color #ccccff
touch_scroll_multiplier 1.5

# Color scheme
foreground #eeeef5
background_opacity 0
selection_foreground #000000
selection_background #eeeef5

# Window layout
confirm_os_window_close 0
map esc close_window
